baseURL = 'https://orgreti.github.io/'
languageCode = 'en-us'
title = 'Reti : An Experimental Filesystem'
description= 'An Experimental Filesystem for Educational Purposes'
theme = "silari"

copyright = "Reti Authors"
enableGitInfo = true

[params]
copyrightStartYear = 2022
sourceURL= "https://github.com/orgreti/orgreti.github.io.git"
licenseURL= "https://creativecommons.org/licenses/by/4.0/"
licenseImageURL= "https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg"
licenseImageAlt= "Creative Commons Attribution 4.0 International License"
licenseSPDX="CC-BY-4.0"


[menu]

[[menu.main]]
name = "Blog"
pre = "blog"
url = "/blog/"
weight = 1

[markup.highlight]
  style ="manni"
  pygmentsOptions = "linenos=table"


[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
